services:
  - type: web
    name: receipt-ocr-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn ocr_receipt:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
